#cloud-config
package_update: true
package_upgrade: true
packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
runcmd:
  - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
  - add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose
  - systemctl start docker
  - systemctl enable docker
  - mkdir -p /mnt/bennetfts_persist
  - mount -o discard,defaults,noatime /dev/disk/by-id/scsi-0DO_Volume_bennetfts-persist /mnt/bennetfts_persist
  - docker run -d -v /var/run/docker.sock:/var/run/docker.sock -v /mnt/bennetfts_persist/portainer_data:/data --name Portainer -p 9000:9000/tcp portainer/portainer-ce
  - docker run -d -v /mnt/bennetfts_persist/fts_data:/data --name BenNetFTS -p 8080:8080/tcp -p 8086:8086/tcp -p 8087:8087/tcp -p 8089:8089/tcp -p 8443:8443/tcp -p 19023:19023/tcp -p 5000:5000/tcp -e PUID=1000 -e GUID=1000 -e FTS_CONNECTION_MESSAGE=BenNetFTS -e FTS_COT_TO_DB=null freetakteam/freetakserver:1.7.5

  
final_message: "The system is up, after $UPTIME seconds"
